# common config for API testing
---
name: common configuration parameters
description: common configuration parameters
variables:
  protocol: http
  host: 172.16.3.1
  port: 5050
  badchars: "!@#$%^&*()[]\":;"
  standard_user: "user1"
